const demoProperties = [
    {
      "id": "1",
      "title": "Cozy Cottage",
      "description": "A charming cottage in the countryside.",
      "propertyType": "Cottage",
      "address": "123 Country Lane",
      "geoLocation": [34.0522, -118.2437],
      "direction": "North",
      "area": [120, 100],
      "regularPrice": 300000,
      "discountPrice": 280000,
      "bathrooms": 2,
      "bedrooms": 3,
      "furnished": true,
      "parking": 1,
      "offer": true,
      "endDate": "2024-06-06T00:00:00.000Z",
      "imageUrls": ["https://example.com/images/1.jpg", "https://example.com/images/2.jpg"],
      "userRef": "user1"
    },
    {
      "id": "2",
      "title": "Modern Flat",
      "description": "A sleek and modern flat in the city.",
      "propertyType": "Flat",
      "address": "456 City Street",
      "geoLocation": [40.7128, -74.0060],
      "direction": "East",
      "area": [90, 80],
      "regularPrice": 450000,
      "discountPrice": 430000,
      "bathrooms": 1,
      "bedrooms": 2,
      "furnished": false,
      "parking": 0,
      "offer": false,
      "endDate": "2024-06-06T00:00:00.000Z",
      "imageUrls": ["https://example.com/images/3.jpg", "https://example.com/images/4.jpg"],
      "userRef": "user2"
    },
    {
      "id": "3",
      "title": "Spacious Farm",
      "description": "A large farm with plenty of land.",
      "propertyType": "Farm",
      "address": "789 Farm Road",
      "geoLocation": [36.7783, -119.4179],
      "direction": "West",
      "area": [500, 150],
      "regularPrice": 800000,
      "discountPrice": 780000,
      "bathrooms": 3,
      "bedrooms": 4,
      "furnished": true,
      "parking": 2,
      "offer": true,
      "endDate": "2024-06-06T00:00:00.000Z",
      "imageUrls": ["https://example.com/images/5.jpg", "https://example.com/images/6.jpg"],
      "userRef": "user3"
    },
    {
      "id": "4",
      "title": "Urban Office",
      "description": "A modern office space in the city center.",
      "propertyType": "Office",
      "address": "1010 Business Ave",
      "geoLocation": [37.7749, -122.4194],
      "direction": "South",
      "area": [200, 200],
      "regularPrice": 600000,
      "discountPrice": 590000,
      "bathrooms": 2,
      "bedrooms": 0,
      "furnished": false,
      "parking": 3,
      "offer": false,
      "endDate": "2024-06-06T00:00:00.000Z",
      "imageUrls": ["https://example.com/images/7.jpg", "https://example.com/images/8.jpg"],
      "userRef": "user4"
    },
    {
      "id": "5",
      "title": "Luxury Villa",
      "description": "A luxurious villa with stunning views.",
      "propertyType": "Villa",
      "address": "1212 Ocean Drive",
      "geoLocation": [25.7617, -80.1918],
      "direction": "East",
      "area": [350, 300],
      "regularPrice": 1200000,
      "discountPrice": 1150000,
      "bathrooms": 4,
      "bedrooms": 5,
      "furnished": true,
      "parking": 2,
      "offer": true,
      "endDate": "2024-06-06T00:00:00.000Z",
      "imageUrls": ["https://example.com/images/9.jpg", "https://example.com/images/10.jpg"],
      "userRef": "user5"
    },
    {
      "id": "6",
      "title": "Downtown Studio",
      "description": "A compact studio apartment in downtown.",
      "propertyType": "Studio",
      "address": "1313 Central Ave",
      "geoLocation": [34.0522, -118.2437],
      "direction": "North",
      "area": [50, 50],
      "regularPrice": 200000,
      "discountPrice": 195000,
      "bathrooms": 1,
      "bedrooms": 0,
      "furnished": false,
      "parking": 1,
      "offer": false,
      "endDate": "2024-06-06T00:00:00.000Z",
      "imageUrls": ["https://example.com/images/11.jpg", "https://example.com/images/12.jpg"],
      "userRef": "user6"
    },
    {
      "id": "7",
      "title": "Retail Mall",
      "description": "A bustling retail mall in a prime location.",
      "propertyType": "Mall",
      "address": "1414 Commerce Blvd",
      "geoLocation": [39.7392, -104.9903],
      "direction": "South",
      "area": [1000, 900],
      "regularPrice": 5000000,
      "discountPrice": 4950000,
      "bathrooms": 10,
      "bedrooms": 0,
      "furnished": true,
      "parking": 100,
      "offer": true,
      "endDate": "2024-06-06T00:00:00.000Z",
      "imageUrls": ["https://example.com/images/13.jpg", "https://example.com/images/14.jpg"],
      "userRef": "user7"
    },
    {
      "id": "8",
      "title": "Warehouse Storage",
      "description": "A large warehouse for storage purposes.",
      "propertyType": "Storage",
      "address": "1515 Industrial Park",
      "geoLocation": [41.8781, -87.6298],
      "direction": "West",
      "area": [800, 750],
      "regularPrice": 700000,
      "discountPrice": 690000,
      "bathrooms": 2,
      "bedrooms": 0,
      "furnished": false,
      "parking": 10,
      "offer": false,
      "endDate": "2024-06-06T00:00:00.000Z",
      "imageUrls": ["https://example.com/images/15.jpg", "https://example.com/images/16.jpg"],
      "userRef": "user8"
    },
    {
      "id": "9",
      "title": "Workshop Space",
      "description": "An open workshop space with high ceilings.",
      "propertyType": "Workshop",
      "address": "1616 Workshop Road",
      "geoLocation": [47.6062, -122.3321],
      "direction": "North",
      "area": [250, 200],
      "regularPrice": 400000,
      "discountPrice": 390000,
      "bathrooms": 1,
      "bedrooms": 0,
      "furnished": false,
      "parking": 5,
      "offer": true,
      "endDate": "2024-06-06T00:00:00.000Z",
      "imageUrls": ["https://example.com/images/17.jpg", "https://example.com/images/18.jpg"],
      "userRef": "user9"
    },
    {
      "id": "10",
      "title": "Palatial Residence",
      "description": "A magnificent palace with grand architecture.",
      "propertyType": "Palace",
      "address": "1717 Palace Way",
      "geoLocation": [51.5074, -0.1278],
      "direction": "East",
      "area": [1500, 1400],
      "regularPrice": 20000000,
      "discountPrice": 19500000,
      "bathrooms": 10,
      "bedrooms": 12,
      "furnished": true,
      "parking": 50,
      "offer": true,
      "endDate": "2024-06-06T00:00:00.000Z",
      "imageUrls": ["https://example.com/images/19.jpg", "https://example.com/images/20.jpg"],
      "userRef": "user10"
    }
  ];

  export default demoProperties;